In [ ]:
#Wine Project

In [2]:
import pandas as pd

In [16]:
# Reading the data from file
wine_df = pd.read_csv('wine.csv')
wine_df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6491.000000,6497.000000,6494.000000,6497.000000,6482.000000,6487.000000,6497.000000
mean,7.214586,0.339632,0.318649,5.443508,0.056031,30.535805,115.738941,0.994596,3.218662,0.531403,10.494394,5.818378
std,1.296304,0.164620,0.145325,4.758042,0.035032,17.756039,56.518925,0.002998,0.160795,0.148912,1.193098,0.873255
min,3.799620,0.079992,0.000000,0.600030,0.009000,1.000050,5.999700,0.987011,2.720136,0.219978,8.000800,3.000000
25%,6.399360,0.229977,0.250013,1.800090,0.037998,17.000850,76.996150,0.992241,3.110156,0.429957,9.500950,5.000000
50%,6.999300,0.289971,0.310016,3.000150,0.046998,29.001450,117.994100,0.994786,3.210161,0.509949,10.301030,6.000000
75%,7.699230,0.399960,0.390020,8.100405,0.064997,41.002050,155.992200,0.996890,3.320166,0.599940,11.301130,6.000000
max,15.898410,1.579842,1.660083,65.803290,0.610969,289.014450,439.978000,1.038876,4.010201,1.999800,14.901490,9.000000

In [4]:
wine_df.shape

(6497, 13)

In [5]:
wine_df.isna().mean()

fixed acidity           0.000000
volatile acidity        0.000000
citric acid             0.000000
residual sugar          0.000000
chlorides               0.000000
free sulfur dioxide     0.000924
total sulfur dioxide    0.000000
density                 0.000462
pH                      0.000000
sulphates               0.002309
alcohol                 0.001539
Type                    0.000000
quality                 0.000000
dtype: float64

In [15]:
#wine_df = wine_df.loc[:,wine_df.isna().mean()<0.50]
wine_df.head(20)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,Type,quality
0,7.39926,0.964904,0.000000,2.200110,0.087996,16.000800,31.99840,0.997460,3.580179,0.669933,10.20102,White,5
1,12.29877,0.389961,0.630032,2.300115,0.090995,6.000300,17.99910,1.000300,3.160158,0.489951,9.50095,White,5
2,6.39936,0.269973,0.490025,7.300365,0.045998,53.002650,205.98970,0.995500,3.240162,0.429957,9.20092,Red,6
3,7.39926,0.189981,0.300015,12.800640,0.052997,48.502425,228.98855,0.998500,3.140157,0.489951,9.10091,Red,7
4,6.19938,0.339966,0.300015,11.100555,0.046998,28.001400,236.98815,0.998000,3.180159,0.489951,8.70087,Red,5
5,4.99950,0.609939,0.120006,1.300065,0.009000,65.003250,99.99500,0.987301,3.260163,0.369963,13.50135,Red,5
6,7.29927,0.409959,0.290015,1.800090,0.031998,26.001300,73.99630,0.988791,2.960148,0.349965,13.00130,Red,8
7,6.59934,0.229977,0.180009,8.500425,0.043998,59.002950,187.99060,0.995480,3.160158,0.489951,9.50095,Red,5
8,5.99940,0.359964,0.160008,6.300315,0.035998,36.001800,190.99045,0.994101,3.170159,0.619938,9.80098,Red,5
9,6.59934,0.209979,0.290015,5.350268,0.028999,43.002150,105.99470,0.991021,2.930147,0.429957,11.50115,Red,7
10,10.59894,0.279972,0.390020,15.500775,0.068997,6.000300,22.99885,1.002500,3.120156,0.659934,9.20092,White,5
11,7.69923,0.389961,0.280014,4.900245,0.034998,36.001800,108.99455,0.991701,3.190160,0.579942,12.20122,Red,7
12,7.49925,0.229977,0.360018,7.000350,0.035998,43.002150,160.99195,0.993701,3.040152,0.319968,11.00110,Red,5
13,9.09909,0.279972,0.460023,9.000450,0.113994,3.000150,8.99955,0.998910,3.180159,0.599940,10.90109,White,6
14,6.69933,0.179982,0.280014,10.200510,0.038998,29.001450,114.99425,0.994591,3.110156,0.449955,10.90109,Red,7
15,7.39926,0.489951,0.270014,2.100105,0.070996,14.000700,24.99875,0.993781,3.350168,0.629937,12.00120,White,6
16,5.89941,0.169983,0.280014,0.700035,0.026999,5.000250,27.99860,0.989751,3.130157,0.319968,10.60106,Red,5
17,8.49915,0.219978,0.340017,0.700035,0.039998,5.000250,24.99875,0.991701,3.040152,0.369963,10.50105,Red,4
18,7.69923,0.419958,0.380019,8.100405,0.060997,49.002450,143.99280,0.996500,3.400170,0.579942,11.00110,Red,6
19,6.59934,0.149985,0.340017,5.100255,0.054997,34.001700,124.99375,0.994101,3.360168,0.419958,9.60096,Red,5

In [8]:
wine_df.Type.value_counts()

Red      4898
White    1599
Name: Type, dtype: int64